---
title: "Admissions"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bootswatch: "sandstone"
    
runtime: shiny
---

```{r}
# Import Libraries
library(bslib)
library(flexdashboard)
library(tidyverse)
library(shiny)
library(gt)
library(DT)

# Read in data
admit = read.csv("cleaned_admissions_data.csv")
```

# Distribution of Statistics

## Column {.sidebar}

```{r}

# Create buttons to select admissions metric
radioButtons(
  "metric", label = "Admission Metric",
  choices = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score"), 
  selected = "gpa"
)

```

## Column

```{r}

admitted_tb = admit %>%
  filter(decision == "Admit") %>%
  summarise("Med. GPA" = median(gpa),
            "Med. Test" = median(test_score),
            "Med. Writing" = median(writing_score),
            "Males" = sum(gender == "Male"),
            "Females" = sum(gender == "Female")) %>%
  pivot_longer(c("Med. GPA","Med. Test","Med. Writing","Males","Females"), names_to = "Statistic", values_to = "Values")

knitr::kable(admitted_tb)
```

## Column

```{r}
# Create label names
admit_options = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score",
              "Work Experience" = "work_exp",
              "Volunteer Level" = "volunteer_level")

# Render plot in shiny
renderPlot({
  ggplot(data = admit[admit$decision == "Admit",], aes_string(x = input$metric)) +
    
    # Create histogram
    geom_boxplot(color = "darkblue", alpha = .7, bins = 10) +
    geom_text(aes_string(x = ".5", y = mean(input$metric), label = mean(input$metric) )) +
    coord_flip() +
    
    # Add axis labels and titles
    labs(title = paste("Summary of Admitted Students", names(admit_options[which(admit_options == input$metric)])),
         y = names(admit_options[which(admit_options == input$metric)])) +
    
    scale_x_continuous(limits = c(min(admit[,input$metric][admit$decision == "Admit"]), 
                                  max(admit[,input$metric][admit$decision == "Admit"]))) +
    
  # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Edit axis text sizes
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    
    # Change facet labels
    strip.text.x = element_text(size = 14, face = "bold"),
    strip.background = element_blank(),
    
    # Clean plot background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
  },
# Change dimensions of figure
height = 600, width = 900)

```



# By Admission

## Column

```{r}
# Render plot in shiny
renderPlot({
  ggplot(data = admit, aes(x = state,fill = decision)) +
    
    # Create bar chart of students by state
    geom_bar( alpha = .7, bins = 10) +
    
    # Facet chart by admission decision
    facet_wrap(~ decision) +
    
    # Coloring of bars
    scale_fill_brewer(type = "qual",
                      palette = "Set2", 
                      name = "Admission Decision") +
    
    # labelling
    labs(title = "Admission Decision by  State",
         y = "Number of Students",
         x = "State" )+
      
    # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Change axis text
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    
    # Cange facet titles
    strip.text.x = element_text(size = 14, face = "bold"),
    strip.background = element_blank(),
    
    # Change legend text sizes
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13),
    
    # Remove backgrounds from legend
    legend.box.background = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    
    # Fix background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
}, 

# Change figure size
height = 700, width = 1590)
```

# Stats by State

## Column {.sidebar}

Different Admissions Metrics

```{r}

# Create buttons to select admissions metric
radioButtons(
  "metric_1", label = "Admission Metric",
  choices = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score"), 
  selected = "gpa"
)

```

## Column

```{r}
# Create label names
admit_options = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score",
              "Work Experience" = "work_exp",
              "Volunteer Level" = "volunteer_level")

# Render plot in shiny
renderPlot({
  ggplot(data = admit, aes_string(x = input$metric_1)) +
    
    # Create histogram
    geom_histogram(fill = "darkblue", alpha = .7, bins = 10) +
    
    # Facet by state
    facet_wrap(~ state, ncol = 3) +
    
    # Add axis labels and titles
    labs(title = paste(names(admit_options[which(admit_options == input$metric_1)]),
                       "From Each State"),
         y = "Number of Students",
         x = names(admit_options[which(admit_options == input$metric_1)])) +
    
  # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Edit axis text sizes
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    
    # Change facet labels
    strip.text.x = element_text(size = 14, face = "bold"),
    strip.background = element_blank(),
    
    # Clean plot background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank(),
    
    panel.border = element_rect(colour = "black", fill=NA, size=2))
  },
# Change dimensions of figure
height = 700, width = 1000)
```

# Metric Comparisons

## Column {.sidebar}

View how admissions metrics correlate with one another

```{r}

# Input one
selectInput(
  "x_var", label = "X-axis",
  choices = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score"), 
  selected = "gpa"
)

# Input 2
selectInput(
  "y_var", label = "Y-axis",
  choices = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score"), 
  selected = "test_score"
)

```

## Column

```{r}
# For naming 
admit_options = c("GPA" = "gpa",
              "Test Score" = "test_score",
              "Writing Score" = "writing_score")

# Make state coloring easier to read
admit$state_col = "States with No Admitted Students"
admit$state_col[admit$state == "Florida"] = "States with Admitted Students"
admit$state_col[admit$state == "California"] = "States with Admitted Students"
admit$state_col[admit$state == "Colorado"] = "States with Admitted Students"
admit$state_col[admit$state == "Utah"] = "States with Admitted Students"

# Render plot in shiny
renderPlot({
  ggplot() +
    
    # Create scatter plot, use colors for states and shapes for admissions dec.
    geom_point(data = admit, 
         aes_string(x = input$x_var, 
                    y = input$y_var, 
                    color = "state_col", 
                    shape = "decision"),
         size = 5,
         alpha = .7) +
    
    # Add labels
    labs(title = paste(names(admit_options[which(admit_options == input$x_var)]),
                       "From Each State",
                       names(admit_options[which(admit_options == input$y_var)])),
         y = names(admit_options[which(admit_options == input$y_var)]),
         x = names(admit_options[which(admit_options == input$x_var)])) +
    
    # Coloring for states
    scale_color_manual(values = c("grey","red"), name = "State Admission Status") +
    
    # Name legend for admission decision
    scale_shape(name = "Admission Decision") +

    
    # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Change axis text formatting
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    
    # Change legend text sizes
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13),
    
    # Remove backgrounds from legend
    legend.box.background = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    
    # Clean up background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
}, 

# Change figure size
height = 700, width = 1350)
```

# Work & Volunteer

## Column

```{r}
# Render plot in shiny
renderPlot({
  ggplot(data = admit, aes(x = work_exp, 
                           y = volunteer_level, 
                           color = state_col, 
                           shape = decision)) +
    
    # Create bar chart of students by state
    geom_point( size = 5, alpha = .7) +
    
    labs(title = "Volunteering and Work Experience Levels",
         y = "Volunteer Level",
         x = "Work Experience") +
    
    # Coloring for states
    scale_color_manual(values = c("grey","red"), name = "State Admission Status") +
    
    # Name legend for admission decision
    scale_shape(name = "Admission Decision") +

    
    # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Change axis text formatting
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    
    # Change legend text sizes
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13),
    
    # Remove backgrounds from legend
    legend.box.background = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    
    # Clean up background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
}, 

# Change figure size
height = 700, width = 1350)
```

# New Admissions Metric

```{r}
admit_normalized = admit
admit_normalized$gpa = scale(admit_normalized$gpa)
admit_normalized$work_exp = scale(admit_normalized$work_exp)
admit_normalized$test_score = scale(admit_normalized$test_score)
admit_normalized$writing_score = scale(admit_normalized$writing_score)
admit_normalized$volunteer_level = scale(admit_normalized$volunteer_level)

admit_normalized = admit_normalized %>%
  summarise(decision = decision,
            state = state,
            state_col = state_col,
            total_score = gpa + work_exp + test_score + writing_score + volunteer_level)

# Render plot in shiny
renderPlot({
  ggplot(data = admit_normalized, aes(x = decision, 
                           y = total_score, 
                           color = state_col
                           )) +
    
    # Create bar chart of students by state
    geom_point( size = 5, alpha = .7) +
    
    labs(title = "Normalized Total Student Score",
         y = "Score",
         x = "Admission Status") +
    
    # Coloring for states
    scale_color_manual(values = c("grey","red"), name = "State Admission Status") +

    
    # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Change axis text formatting
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    
    # Change legend text sizes
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13),
    
    # Remove backgrounds from legend
    legend.box.background = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    
    # Clean up background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
}, 

# Change figure size
height = 700, width = 1350)




```

# New Eligible Students

## Column

```{r}
# Render plot in shiny
renderPlot({
  ggplot(data = admit_normalized[admit_normalized$total_score >= -1,], 
         aes(x = state, fill = state_col)) +
    
    # Create bar chart of students by state
    geom_bar( alpha = .7) +
    
    # Coloring of bars
    scale_fill_manual(values = c("grey","red"), name = "State Admission Status") +
    
    # labeling
    labs(title = "Eligible Students for Admission with New Metric",
         y = "Number of Students",
         x = "State" )+
      
    # Change theme
  theme(
    # Enlarge & center title
    plot.title = element_text(
      size = 25, 
      margin = margin(10, 0, 10, 0), hjust = .5
    ),
    
    # Change axis text
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 16),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    
    # Cange facet titles
    strip.text.x = element_text(size = 14, face = "bold"),
    strip.background = element_blank(),
    
    # Change legend text sizes
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 13),
    
    # Remove backgrounds from legend
    legend.box.background = element_blank(),
    legend.background = element_blank(),
    legend.key = element_blank(),
    
    # Fix background
    panel.grid.minor = element_line(color = "#D3D3D3", size = 0.2),
    panel.grid.major = element_blank(), # Remove major grid
    panel.background = element_blank())
}, 

# Change figure size
height = 700, width = 1400)
```

# New Admissions Stats


## Column

```{r}

admitted_tb = admit %>%
  filter(decision == "Admit") %>%
  summarise("Med. GPA" = median(gpa),
            "Med. Test" = median(test_score),
            "Med. Writing" = median(writing_score),
            "Males" = sum(gender == "Male"),
            "Females" = sum(gender == "Female")) %>%
  pivot_longer(c("Med. GPA","Med. Test","Med. Writing","Males","Females"), names_to = "Statistic", values_to = "Values")

admitted_tb_new = admit[admit_normalized$total_score >= -1,] %>%
  summarise("Med. GPA" = median(gpa),
            "Med. Test" = median(test_score),
            "Med. Writing" = median(writing_score),
            "Males" = sum(gender == "Male"),
            "Females" = sum(gender == "Female")) %>%
  pivot_longer(c("Med. GPA","Med. Test","Med. Writing","Males","Females"), names_to = "Statistic", values_to = "Values")

admitted_tb = admitted_tb %>%
  left_join(admitted_tb_new, by = c("Statistic" = "Statistic"))
colnames(admitted_tb) = c(" ","Current Admissions", "With New Admission Metric")

knitr::kable(admitted_tb)
```

